name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm --version
      - run: npm install
      - run: npm run build -w packages/e2ee
      - run: npm run build -w packages/sdk
      - run: npm run lint -w packages/e2ee
      - run: npm run lint -w packages/sdk
      - run: npm run test -w packages/sdk
      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: sora-devtools
          SLACK_COLOR: danger
          SLACK_TITLE: Failure test
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
